SELECT DEPT_EMP.DEPT_NO,
	DEPT_NAME,
	EMPLOYEES.EMP_NO,
	LAST_NAME,
	FIRST_NAME
FROM ((EMPLOYEES
		INNER JOIN DEPT_EMP ON DEPT_EMP.EMP_NO = EMPLOYEES.EMP_NO)
			INNER JOIN DEPARTMENTS ON DEPT_EMP.DEPT_NO = DEPARTMENTS.DEPT_NO);