SELECT DEPT_NAME,
	EMPLOYEES.EMP_NO,
	LAST_NAME,
	FIRST_NAME
FROM ((DEPARTMENTS
	INNER JOIN DEPT_EMP ON DEPARTMENTS.DEPT_NO = DEPT_EMP.DEPT_NO)
		INNER JOIN EMPLOYEES ON EMPLOYEES.EMP_NO = DEPT_EMP.EMP_NO)
WHERE DEPARTMENTS.DEPT_NAME in ('Sales', 'Development');